<?php

namespace AppBundle\Repository;

/**
 * CatalogTabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogTabRepository extends \Doctrine\ORM\EntityRepository
{
}
