<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVhs7nk4\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVhs7nk4/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVhs7nk4.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVhs7nk4\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVhs7nk4\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vhs7nk4',
    'container.build_id' => 'b432f1aa',
    'container.build_time' => 1526655153,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVhs7nk4');
